# Generated by Django 5.2.6 on 2025-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maj_app', '0002_plant_delete_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('discount_price', models.FloatField(null=True)),
                ('mrp', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='plant',
        ),
    ]
