# Generated by Django 5.2.6 on 2025-10-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maj_app", "0006_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
