# Generated by Django 5.2.6 on 2025-10-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maj_app", "0007_order_is_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
    ]
